spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: adidas
    password: adidas
    driver-class-name: org.h2.Driver

---

spring:
  profiles: docker

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URI}
